# Generated by Django 4.2.5 on 2024-02-08 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designation', '0001_initial'),
        ('department', '0001_initial'),
        ('employee', '0003_employee_emp_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diciplinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_personal_id', models.CharField(max_length=500)),
                ('date_of_diciplinary', models.DateField()),
                ('diciplinary_reason_name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.departments')),
                ('desig_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designation.designation')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
