# Generated by Django 4.2.5 on 2024-01-29 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('designation', '0001_initial'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500, unique=True)),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('emp_id', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('dob', models.DateTimeField()),
                ('nid', models.IntegerField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('blood_group', models.CharField(max_length=500)),
                ('joining_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField()),
                ('address', models.TextField()),
                ('photo', models.ImageField(default='No images', upload_to='media/')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.departments')),
                ('designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designation.designation')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.role')),
            ],
        ),
    ]
