# Generated by Django 4.2.5 on 2024-02-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_dob_alter_employee_emp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_status',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
