# Generated by Django 4.2.5 on 2024-02-12 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_employee_emp_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendence_date', models.DateTimeField(auto_now_add=True)),
                ('signin_time', models.DateTimeField(auto_now_add=True)),
                ('signout_time', models.DateTimeField(blank=True, null=True)),
                ('working_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
