# Generated by Django 4.2.5 on 2024-02-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_signin_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='working_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
