# Generated by Django 4.2.5 on 2024-02-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_working_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendence_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
